CREATE TABLE notes (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1019 INCREMENT BY 97),
  "target" INT NOT NULL REFERENCES "elements" ("id"),
  "title" VARCHAR(300) DEFAULT '',
  "tags" VARCHAR(300) DEFAULT '',
  "desc" TEXT DEFAULT '',
  "created" INT NOT NULL,
  "created_by" INT NOT NULL,
  "updated" INT NOT NULL,
  "updated_by" INT NOT NULL,
  "status" SMALLINT DEFAULT 0
);
