CREATE TABLE relations (
  "id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "active_name" VARCHAR(100) NOT NULL,
  "passive_name" VARCHAR(100) NOT NULL,
  "is_active" BOOL DEFAULT true,
  "created" INT NOT NULL,
  "created_by" INT NOT NULL,
  "updated" INT NOT NULL,
  "updated_by" INT NOT NULL,
  "status" SMALLINT DEFAULT 0
);
